### ISSUE TITLE
mass-produce styrofoam holders

### ISSUE THREAD

**Issue by Iepoev** [ZeusWPI/12urenloop#104]
- [x] purchase ikea boxes
- [x] purchase styrofoam (schleiper)
- [x] carve styrofoam

**Comment by Silox** [comment]
We need 5 protector boxes for 6 gyrids. The unprotected one will stand in the container.

**Comment by Iepoev** [comment]
http://www.ikea.com/be/nl/catalog/products/S79850875/#/S79850875

**Comment by SirDestrox** [comment]
will help on monday
