### ISSUE TITLE
analyze twitter output for faults

### ISSUE THREAD

**Issue by Iepoev** [ZeusWPI/12urenloop#113]

**Comment by Iepoev** [comment]
twitter output can be found at twitter.com/12ultest

**Comment by iasoon** [comment]
Has this been done?

**Comment by Iepoev** [comment]
"fastest lap yet" doenst work correctly

**Comment by Iepoev** [comment]
`total laps` works correctly

**Comment by Iepoev** [comment]
`total distance` also works correctly

**Comment by mivdnber** [comment]
> "fastest lap yet" doenst work correctly
Isn't it wildly inaccurate anyhow?
