### ISSUE TITLE
Stuff to buy 2016

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/12urenloop#126]
- [x] evt. Netwerkkabel (TBD, hangt af van internetaansluiting, #130) (80 euro / 305m)
- [x] Cartridge voor labelmaker (20 euro (?))
- [x] 100 batterijen (20 euro)
- [x] evt. Bluetooth chips (TBD, moet nog getest worden, #130)

**Comment by NoctuaNivalis** [comment]
[ ] Lock to prevent waste of labelmaker tape (?)

**Comment by Iepoev** [comment]
labelmakercartridge has been bought and installed

**Comment by Iepoev** [comment]
labelmaker has been labeled with a "MISBRUIK = 1 STREEPJE" label

**Comment by Procrat** [comment]
Batteries & one extra roll of UTP-cable was bought.
