### ISSUE TITLE
Fix internet

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/12urenloop#128]
- [x] Trying Digipolis
- [x] Try lasering from GUSB from across the watersportbaan
- [x] Try ISPs
- [x] Try asking the person in charge of the personal training cabin.
- [ ] Try asking the rowing clubs again.
- [ ] Settling for a 4G router.

**Comment by NoctuaNivalis** [comment]
I am in favor of lasering internet across the river.

**Comment by Procrat** [comment]
Could you elaborate, @NoctuaNivalis?

**Comment by NoctuaNivalis** [comment]
Sure thing @Procrat, there you go:
```
  .------.
  | GUSB |            LASER             .-----------.
__|      >---------o----o--------o----->| CONTAINER |_______
         |                              |
         |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
         |        WATERSPORTWATER       |
         '------------------------------'
```

**Comment by Procrat** [comment]
We received some lasers to test with. ^^

**Comment by becousae** [comment]
Testing the lasers on s9 was successful. Nobody was killed.

**Comment by NoctuaNivalis** [comment]
And how exactly is that successful?

**Comment by Procrat** [comment]
- Both DICT and the people responsible at GUSB were very wary. They also suggested asking rowing clubs or doing it with a 4G router anyway.
- The rowing club at the right side of the water was closed when I went and is apparently only open two hours in a week.
- There's a cabin next to the rowing club that is lent to personal trainers. I got the contact info of the owner of these cabins. I will contact him later today.

**Comment by Procrat** [comment]
As for the ISPs:
- Belgacom (actually Proximus) gave us an offer of €58 (excl. btw) for the subscription + €59 for the installation.
- Telenet didn't reply, even after a reminder mail.

**Comment by Procrat** [comment]
I phoned the owner of the personal trainer cabin. We still have to work out the details, but he seemed quite willing to share his internet connection (maybe in exchange for some advertising).
I'll update as soon as I hear more.

**Comment by Procrat** [comment]
Leander Verbraeken is an awesome guy!
