### ISSUE TITLE
Material for 2016

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/12urenloop#133]
*Network*
- [ ] Managed switch (from Zeus)
- [ ] Router (Token)
- [ ] Two Wifi APs (both from Zeus)
- [ ] Network cable
- [ ] Network cable making stuff: connectors, cable shields, pliers, tester
- [ ] 4G router (from Zeus) as backup

*PCs and stuff for us & Saruman*
- [ ] Something for running count-von-count (@becousae's laptop)
- [ ] A GNU/Linux-client as backup (came in handy last time. Token perhaps?)
- [ ] 6 laptops for us + Saruman (from DICT, @Iepoev)
- [ ] 3 screens for us (from Zeus)
- [ ] 2 screens for Saruman (from Zeus)
- [ ] 5 mice (2 for Saruman, 3 for us)
- [ ] 3 keyboards
- [ ] 2 barcode scanners for Saruman (from FK, @Procrat)

*Counting infrastructure*
- [ ] 26 batons
- [ ] AA-batteries
- [ ] 7 Gyrids (from geology dep, @Iepoev)
- [ ] Batteries for Gyrids (frpm geology dep, @Iepoev)
- [ ] Two tablets for manual counting (one from @Silox, one from @feliciaan)

*SMS system for DJ contest*
- [ ] Cell phone
- [ ] Deadpool

*Other stuff*
- [ ] UPS (+ cables)
- [ ] Power cables
- [ ] Verdeelstekkers
- [ ] Label machine
- [ ] Soldeerbout
- [ ] Battery tester
- [ ] VGA switcher
- [ ] Some adapters and shit (HDMI adapter, ...)

NB. Duct tape, spanbandjes and electrical tape should be delivered by BAD.

**Comment by Procrat** [comment]
Staat nog niet klaar:
- [ ] 4G-router
- [ ] Wifi AP
- [ ] Verdeelstekkers

**Comment by Iepoev** [comment]
current checkmarks signify wether or not these are prepared on the table

**Comment by Procrat** [comment]
Delivered.
