### ISSUE TITLE
Improve website

### ISSUE THREAD

**Issue by javache** [ZeusWPI/12urenloop#63]
Some random issues people can work on:

* [x] Give live.12urenloop.be a nice layout
* [x] Add a timetable of special laps
* [ ] Add a photo section with links to photo-albums of previous years
* [x] Integrate some basic scores with boxxy, add a banner or something on top to visit live.12urenloop.be
* [ ] Integrate video-stream (details yet unknown)

**Comment by Procrat** [comment]
@becousae Implemented this in d04999fe79a320e56bc2b4b3773a13c3a2f27d7a
