### ISSUE TITLE
Boxxy forgets all results when frozen

### ISSUE THREAD

**Issue by Javache** [ZeusWPI/12urenloop#67]

**Comment by FelixVanderJeugt** [comment]
I think @nudded and I managed to fix this last year, but I'm not entirely sure. Will test and and fix/close.

**Comment by Silox** [comment]
:+1:


On 25 Mar 2015 at 19:49:07, Felix Van der Jeugt (notifications@github.com) wrote:

I think @nudded and I managed to fix this last year, but I'm not entirely sure. Will test and and fix/close.
