### ISSUE TITLE
Bill of materials 2015

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/12urenloop#84]
List up all the hardware we will bringing this year. Use the checkboxes for marking stuff as collected, and retrieved back at the home base.

* **Networking**
  * [x] Managed switch (Student Kick-Off)
  * [x] Multiple WiFi base stations
  * [x] Network cable
     * Can we mark all Zeus-cable?
     * Old cable should be thoroughly tested (iperf etc) so we can rely on STP
     * All cables should have working and shielded RJ45-connectors
   * [x] Network cable making stuff: connectors, cable shields, pliers, tester
* **Wireless stuff**
  * [x] Heavy wifi router ( @Procrat )
  * [x] 4G router thing (@Don wil buy this @ Codima)
  * [x] 4G dual band stick (Jan has this)
  * [x] 4G Sim card (FK has some of these)
* **PC's**
  * [x] Router and other small stuff (Token)
  * [x] Something for running boxxy, count-von-count and sihemo
  * [x] Laptop for the rest of the organisation (Windows 7)
  * [x] Laptop for the videowall
  * [x] 7 Laptops for Saruman
  * [x] 2 barcodescanners (FK)
  * [x] Reserve laptop
  * [x] 3 big screens
* **Counting infrastructure**
  * [x] 26 batons
     * Identify them with A,B,C,...
  * [x] AA-batteries
  * [x] Battery-tester
  * [x] 6-7 Gyrid devices with battery
  * [x] UPS for counting systems
  * [x] Label-machine
  * [x] Soldeerbout
* **Manual counting**
  * [x] Two tablets (iPads?) for the manual count
* **SMS hot/not stuff**
  * [x] Cell phone for Gammu
  * [x] Desktop? Deadpool? Jordy's Pi?
  * [x] Check sim card (put some money on it)
* **Other stuff**
  * [x] Domino stekkers
  * [x] UPS
  * [x] Power cables (min. 4 we can connect to the UPS!)

**Comment by FelixVanderJeugt** [comment]
lol STP
