### ISSUE TITLE
Stuff to buy 2015

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/12urenloop#85]
- [x] Roll of Cat5 network cable (305 meters)
- [x] 4G ac dual band USB sim-card-holder-stick-thing (https://www.codima.be/tp-link-3g-4g-wireless-n-router)
- [x] 100 batteries from IKEA. Check how many new ones we still have
- [x] Boxes stuff
  - [x] IKEA plastic boxes (@iepoev what dimensions?)
  - [x] Isemo
  - [x] White paint

**Comment by Iepoev** [comment]
network cable is bought. Don will buy batteries.

the specific model number of the sim-card-holder-thing is required before making a purchase.

**Comment by Donvittorio** [comment]
Batteries have been bought
