### ISSUE TITLE
Test cell phone, counting script and put credit on the card

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/12urenloop#87]
- [x] Test cell phone
- [x] Test counting script
- [x] Put credit on card

**Comment by Silox** [comment]
@Iepoev could you put credit on the old Nokia card? Shmetta knows the number, I believe it's a proximus one.

**Comment by Iepoev** [comment]
done

**Comment by Silox** [comment]
:+1:

**Comment by Procrat** [comment]
Reopening this for 2016

- [ ] Test cell phone
- [ ] Test counting script
- [ ] Put credit on card

**Comment by Iepoev** [comment]
added 10 Euros of credit to the card (should last us an entire year) and set up a reminder in the  #12urenloop slack channel on 16 march

**Comment by Procrat** [comment]
Done.
