### ISSUE TITLE
Create an automatic sponsor/score loop

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/12urenloop#88]
Put it on a laptop, connect the videowall and don't bother with anything video-related for that day.

**Comment by Procrat** [comment]
The loop between the scores page and the marquee page is done: b4656cfae629fc9ea0fe61a5dc72bc15fe0e6dc0
It just remains to add the sponsors to `/boxxy/videowall/marquee.html`

**Comment by Procrat** [comment]
We're waiting for some extra sponsors from Jordy.
We then only have to adapt the sponsorloop to the marquee loop.

**Comment by Silox** [comment]
These should be added https://drive.google.com/folderview?id=0B1LcyxrrSQoTflFmTGpQTk5jc0Q5QlFua0RZY29pVGt2S3h2YTBUenlJTDJsLW9sSVZ6VFE&usp=sharing#
