### ISSUE TITLE
Configure all the gyrids

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/12urenloop#89]
Make sure everything works; try to put them in a circle

Label them from 101 to 107 (or 108?) and give them a corresponding ip adress (x.y.z.101 eg)

**Comment by Silox** [comment]
* 108: upgrading went wrong here, python was wobbly, abort abort
* 109: OK
* 110: to do
* 121: OK
* 102: to do
* 113: to do
* 330: should be fine (Has a sticker: Valt uit?) but noticed no problems here

**Comment by Silox** [comment]
Everything has network ... Let's try to complete the loop now.

**Comment by Silox** [comment]
Yesh, it works. The loop is there, ports seem to do something. 

![screen shot 2015-04-04 at 00 17 56](https://cloud.githubusercontent.com/assets/915130/6989740/13734a7c-da60-11e4-911a-23d8e0603038.png)

**Comment by Procrat** [comment]
Reopening this for 2016.

**Comment by NoctuaNivalis** [comment]
Note that we should be able to flash all gyrids cards with the device dump we've taken and used last year.

**Comment by Procrat** [comment]
Note for next year: to connect with the serial port, you can use one of [these programs](https://wiki.archlinux.org/index.php/Working_with_the_serial_console) with baud rate 24000, 8 data bits, no parity bit and 1 stopbit.

**Comment by mivdnber** [comment]
Are you sure about that? I always connect at 38400 baud. Easiest is `screen /dev/<PORT> 38400`.

**Comment by Silox** [comment]
2016:

All Connecting to: 10.1.2.178:2583

101: should be ok
102: should be ok
103: should be ok
105: should be ok
112: should be ok
unlabeled 1: no idea
unlabeled 2: no idea

**Comment by Silox** [comment]
Current status: gyrids should be configured correctly and are all booting. 
Next todo: check if they actually connect with CVC and send data

**Comment by Silox** [comment]
Fixed the /usr/share/gyrid/network_middleware to s/caching/cache/ on line 675 or something. **NOT DONE FOR 102 YET!!!**

**Comment by Iepoev** [comment]
finished 102 config

**Comment by Iepoev** [comment]
on the topic of stp:

the problem was that the gyrids all have the same bridge priority id (because we are just copypasting the `config/interfaces` file). However, the id in this file is/was lower than the default id of the cisco switch. This resulted in all of the gyrids getting into an ex aequo when electing the root. The solution was to lower the bridge priority id of the switch to 0.

PR #136 resolves this by increasing the bridge priority id of the `config/interfaces` to the maximum value

**Comment by becousae** [comment]
Reopen this for 2017.

**Comment by Iepoev** [comment]
all gyrids have been labeled and have been assigned a correct hostname + ip address
they still need to be patched
https://github.com/ZeusWPI/12urenloop/issues/114#issuecomment-206234613

and  `hwclock -w` has also not been run

**Comment by NoctuaNivalis** [comment]
2017 edition is over. Also kindly open a new issue (with a link here) next year, this issue keeps showing up in my TODO.
