### ISSUE TITLE
Order 6 laptops from DICT + 2 screens + Beamer (?)

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/12urenloop#91]
Mail to dictshop at ugent dot be. Request them from the friday (or thursday) prior to the next friday

**Comment by Silox** [comment]
Requested

**Comment by Silox** [comment]
Reservation is done; they can be picked up early in the afternoon upcoming thursday.

**Comment by Procrat** [comment]
Reopening for 2016. 6 or 7 should be enough.

**Comment by becousae** [comment]
2 screens for donaat

**Comment by becousae** [comment]
And a beamer if possible

**Comment by Procrat** [comment]
@Iepoev ordered 6 laptops.

**Comment by Procrat** [comment]
Picked up.

**Comment by Procrat** [comment]
Returned
