### ISSUE TITLE
Prepare the batons

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/12urenloop#95]
There are 20 teams, so we'll just go for the 26 premade battons and material for +- 5 backup batons to make the day itself.

We need a list from:
Letter -> (Kring, mac-address)

The kringen can be found on the website.

**Comment by FelixVanderJeugt** [comment]
I still have to check the team names, and link them to battons. Best would be to name them in the same order as their tents along the circuit?

**Comment by Silox** [comment]
See the website for the correct oder (ordered by placement of their tents along the circuit indeed). These also are the correct names.
